### Import Libraries

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Import the data set

In [25]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [26]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [27]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the training and testset

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
print(x_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [30]:
print(x_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [31]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [32]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


### Training the Multiple Linear Regression on Training Set

In [33]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Predict the test Set

In [34]:
y_pred = np.array(regressor.predict(x_test))
reshape_test = y_test.reshape(len(y_test),1)
reshape_pred = y_pred.reshape(len(y_pred),1)
np.set_printoptions(precision=2)
np.concatenate((reshape_test, reshape_pred),axis=1)

array([[431.23, 431.43],
       [460.01, 458.56],
       [461.14, 462.75],
       ...,
       [473.26, 469.52],
       [438.  , 442.42],
       [463.28, 461.88]])

In [35]:
print(regressor.coef_)
print(regressor.intercept_)

[-1.97 -0.24  0.06 -0.16]
452.8410371616383


## Evaluating using R square method

In [36]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9325315554761302